version: '3'
services: 
    comments:
        build: ./comments
        ports: 
            - 4001:4001
    event-bus:
        build: ./event-bus
        ports:
            - 4005:4005
    posts:
        build: ./posts
        ports:
            - 4000:4000
    query:
        build: ./query
        ports:
            - 4002:4002
